name: build

on:
  pull_request:
    branches: [main]
    types: [opened]
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package_name: ["nvim-min"]
    steps:
      - uses: actions/checkout@v3

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Magic Nix Cache
        uses: DeterminateSystems/flakehub-cache-action@main

      - name: Run `nix bundle`
        id: build
        run: |
          nix bundle \
            -o ${{ matrix.package_name }}.AppImage \
            --bundler github:ralismark/nix-appimage \
            --extra-experimental-features nix-command \
            --extra-experimental-features flakes .#${{ matrix.package_name }}
          echo "Done building AppImage for ${{ matrix.package_name }}"

      - name: Upload bundle to release
        if: github.ref == 'refs/heads/main'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: "${{ matrix.package_name }}.AppImage"
          asset_name: "${{ matrix.package_name }}-x86_64-linux.AppImage"
          tag: latest
          overwrite: true
